### PR TITLE
cljfmt-compatible indenting for some forms

### LINKED ISSUE #22: cljfmt-compatible ns form formatting
Hello,
Currently `indent/clojure.vim` indents subforms of `(ns ...) ` with 2-spaces, like this:
```
(ns ncr.nsql.simple
  (:require
    [clojure.string :as str]
    [clojure.core.match :refer [match]]
```
while the style guide seemingly recommends, and `cljfmt` indents, the same subforms with 1-space (paren-aligned), like this:

```
(ns ncr.nsql.simple
  (:require
   [clojure.string :as str]
   [clojure.core.match :refer [match]]
```

Would you consider accepting a patch that adds optional, off-by-default ability to format those like `cljfmt` does it?

### PR DESCRIPTION
**Pull request by jsn**
This seems to fix #22 for me.

### CODE REVIEW

**Comment by axvr** [comment]
Thanks, I'll try to review this tomorrow.

**Review by axvr — CHANGES_REQUESTED** [review]
Excellent work.  I've tested it and it works as expected for me.  Although I do have a couple of minor suggestions.

**Review by jsn — COMMENTED** [review]
Added both, thank you!

**Review by axvr — APPROVED** [review]

**Comment by axvr** [comment]
Thanks, merged!

**Pull request merged**
