### PR TITLE
Syntax highlight comment reader macro as a comment

### PR DESCRIPTION
**Pull request by axvr**
| Before | After |
|---|---|
| image | image  |

### CODE REVIEW

**Comment by Deraen** [comment]
Did you compare if this affect the performance?

Quickly comparing one file with and without this, the syntax time doesn't seem to be affected, but this added lots of additional checks.

Also, this doesn't support case with multiple `#_` combined to ignore map key value pairs, like `#_#_:foo "bar"`. Probably unfeasible to support that using regexes.

**Comment by axvr** [comment]
I did test it but didn't add the results here, I'll make sure to do that next time.

When `#_` is used, this PR improved performance as it can stop processing the commented region upon a `#_` match.  When `#_` isn't used there is negligible performance difference.

### With `#_` usages

Test file: https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-with_usage_test-clj

| Before (ms) | After (ms) |
|---|---|
| [0.056664](https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-results_with_before-log) | [0.042818](https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-results_with_after-log) |

### Without `#_` usages

Test file: https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-without_usage_test-clj

| Before (ms) | After (ms) |
|---|---|
| [0.054265](https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-results_without_before-log) | [0.055136](https://gist.github.com/axvr/9bb2665336bb3ec351d5b11d55b1555e#file-results_without_after-log) |

---

I intentionally didn't try to implement stacking `#_#_:foo "bar"` for the reason you mentioned, that would be almost impossible to do that with regular expressions.

**Comment by axvr** [comment]
> One side effect of changing the style for code forms after #_ is that it breaks the indentation. Indentation uses the syntax rules to find forms etc.

You are correct about the indentation issue.  I've pushed a [fix](https://github.com/clojure-vim/clojure.vim/commit/aa9a253c87139ca2812e70f1a993e47b8f39129e) for that.

> Another is that motions that deal with elements, like `ae` used to work inside commented out forms. Maybe also `cpp` or such commands from fireplace or others? Like `(+ ...)` in the example, now these select the whole commented out form.

Would you mind trying them again with the patch I just pushed?  If they still don't work I might make the highlighting of this optional (disabled by default) or revert the change entirely.

> Do you know if we could still parse the commented out forms like previously, but only change the color?

As far as I know, this isn't possible using the syntax file, but "[text properties](https://vimhelp.org/textprop.txt.html)" might be able to.

**Comment by Deraen** [comment]
Indent works now.

Text objects (confused with motions in previous comment) still don't work.

**Comment by Deraen** [comment]
For context:
https://github.com/guns/vim-sexp/blob/master/plugin/sexp.vim#L269
https://github.com/guns/vim-sexp/blob/master/autoload/sexp.vim#L1434

There are some notes about "contained" syntax rules also here:
https://github.com/guns/vim-sexp/blob/master/autoload/sexp.vim#L458-L474

Looking at clojureCommentReaderMacroForm, it is still parsing every form inside the comment, as that is needed anyway to count the parenthesis to find the end of macro form. There is just some small difference in this syntax rule compared to others.

**Comment by axvr** [comment]
I've found the source of the problem.  Vim-sexp will [ignore syntax regions containing "comment"](https://github.com/guns/vim-sexp/blob/12292941903d9ac8151513189d2007e1ccfc95f0/autoload/sexp.vim#L40).  The way to fix this is to rename `clojureCommentReaderMacro` and `clojureCommentReaderMacroForm` to not contain the word "comment".

Now I'm not sure whether I should:
1. rename it,
2. make it optional, or
3. remove the feature entirely.

The fact that it isn't possible to correctly syntax highlight stacked `#_`s is making me lean more towards removing this change.

**Comment by axvr** [comment]
I've pushed a commit to rename it for now although I'm still considering making it optional or removing it.

**Pull request merged**
